### PR TITLE
Fix kibana password

### PR DESCRIPTION
**Pull request by joerg**
Do not use, or better misuse, run_state in this case. It does not work this way, so better just use attribute?
This also fixes Issue #55.

### CODE REVIEW

**Comment by joerg** [comment]
I have no experience so far with Jenkins and this build failure, but it seems that this error is completely unrelated to my pull request...

**Comment by martinb3** [comment]
ok to test

**Comment by martinb3** [comment]
retest this please

**Comment by martinb3** [comment]
@joerg I'm going to move this into https://github.com/rackspace-cookbooks/elkstack/pull/102. Just for some background:

Elkstack is designed to treat Kibana credentials as data not truly owned by the stack. Many users will end up putting nginx configurations that protect Kibana with ldap, htaccess, SAML, etc, and elkstack is intended to remain agnostic about those decisions. `node.run_state` is intended for transient data, so elkstack expects wrapper cookbooks to *own* the credentials data, but pass it to elkstack via `node.run_state` as transient data. Elkstack guarantees it won't persist that data anywhere -- the responsibility lies on the wrapper cookbooks for that.

**Pull request closed without merging**
